name: hemend_async_log_recorder
description: An Extension to the hemend_logger package that enables asynchronously logging
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
  logging: ^1.1.1
dependencies:
  hemend_logger: ^0.1.3+1
  http: ^1.0.0
