name: hemend_async_log_recorder
description: An Extension to the hemend_logger package that enables asynchronously logging
version: 0.1.4+2
repository: https://github.com/FMotalleb/hemend_async_log_recorder

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  logging: ^1.1.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0

dependencies:
  hemend_logger: ">=0.1.4 <1.0.0"
  http: ^1.0.0
  meta: ^1.9.1
